### ISSUE TITLE
Server loading error with Cauldron 1.6.4

### ISSUE THREAD

**Issue by Artres** [MinecraftPortCentral/Cauldron-Issues#119]
I am currently having a problem similar to one Darkness had a few months back. For reference it on this thread: http://cauldron.minecraftforge.net/threads/solved-something-wrong-with-cauldron-1-7-2.40/
Whenever I run the launch.bat it runs normally for a few second before giving me this error:

A problem occurred running the Server launcher.java.lang.reflect.InvocationTarge
tException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.j
ava:43)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.
java:12)
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_6_R3/util/S
erverShutdownThread
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:128)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_6_R3.util
.ServerShutdownThread
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLo
ader.java:186)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 12 more
Caused by: java.lang.NullPointerException
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLo
ader.java:178)
        ... 14 more

My .bat file's code is:
java -Xmx4G -Xms3G -jar cauldron.jar nogui
pause

I am in the United Kingdom so I am assuming it's not an internet problem, I don't think.
Any help would be much appreciated!

**Comment by Artres** [comment]
Fixed Issue, was due to renaming cauldron jars from original names, reinstalled, fixed!
:+1:

**Comment by modderchris** [comment]
what is the fix? I am using default names and it still wont work

**Comment by vico93** [comment]
oh god please, this repo is very dead for now.
If you want to use a Forge+Bukkit server then you need to update to 1.7.10 and use Thermos https://github.com/CyberdyneCC/Thermos

**Comment by modderchris** [comment]
I can't run 1.7.10 until zen comes out because I get sub 10 fps why do people hate 1.6.4 so much at least with that I get 20+ fps

**Comment by vico93** [comment]
So you will not get any help here, because no one of the devs are active anymore (all come to dev Sponge)
