### ISSUE TITLE
BungeeSuiteChat/networkwidechat not working with Cauldron 1.7.10/BS FML

### ISSUE THREAD

**Issue by johnfriedrich** [MinecraftPortCentral/Cauldron-Issues#12]
Hi
I am using BungeeSuite for Networkwide homes/warps/tps/chat for over a year now on spigot servers.
Since we integrated our Cauldron Pixelmon Server in our BungeeCord network we realized that BungeeSuite Plugins are not working.
For example:
You can send /msg from a spigot to the cauldron server, that works fine. (But not chat messages)
But you cannot send send any chat messages to spigot servers.

Cauldron:
git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.187 (MC: 1.7.10)

Latest FML BungeeCord

Trying to chat gives the following error:
https://github.com/Bloodsplat/BungeeSuiteChat/search?utf8=%E2%9C%93&q=Player+did+not+connect+properly+through+BungeeCord%2C+Chat+canceled%21

So I think it's a problem how Cauldron is handling online/offline mode? Or it's the connection between BungeeCord and Cauldron itself?

https://github.com/Bloodsplat/BungeeSuiteChat

May you throw a look on the issue? Could be also a BungeeSuite issue/problem I don't know.

Thanks in advance

**Comment by Katelyn-SN** [comment]
If your running BungeeSuite your likely to have issues it was never upgraded to support 1.7.10 nor does it have UUID support. I recommend moving to geSuit and CloudChat for your system as BungeeSuite is greatly outdated.

**Comment by johnfriedrich** [comment]
I know that but support for gesuit is also dropped since some time and BungeeSuite is working fine for me except this issue.
Anyways, I will give geSuit a try on my dev server.

**Comment by aallen42** [comment]
This is probably caused by the same plugin channel problem which causes this: https://github.com/MinecraftPortCentral/Cauldron-Issues/issues/9

**Comment by bloodmc** [comment]
Fixed in build 206.

**Comment by F4ith93** [comment]
The problem still exist, but more arbitrary.
With build 206 some Users can chat, some dont.

Same Error: Player did not connect properly through BungeeCord, Chat canceled!

All Players, which are connected to the Cauldron-Server can chat when we reload the chat.
If they going to another server and hang around there for some time and then come back
to the Cauldron-Server with /server-Command there got the issue again.

**Comment by johnfriedrich** [comment]
Can confirm, still not working correctly
