### ISSUE TITLE
Bungee -> Cauldron w/ Multiverse = Crash

### ISSUE THREAD

**Issue by ghost** [MinecraftPortCentral/Cauldron-Issues#4]
http://pastebin.com/5YuB3Gee

When logging out in a non-default dimension (eg. one created by Multiverse), logging back in will cause the client to close leaving the crash log left above. This cannot be reproduced with just Cauldron w/ Multiverse without the Bungee instance. Can produce a test instance if needed.

To reproduce, create a Bungee instance and a Cauldron server instance. Put Multiverse-Core on the Cauldron instance and create a new world. Logout of this world, close your Forge client. Then just reopen the client and reconnect to the server, and it should crash.

**Comment by Katelyn-SN** [comment]
Issue currently not present on 1.6.4 as far as i can see.

But i am having the same occurrence on 1.7.10

As this seems like a 1.7.10 isolated issue i would suggest adding  a [1.7.10] to the beginning of the title so we can keep these issues quite defined for blood :)

**Comment by JayPeaSize** [comment]
Can confirm the 1.7.10 issue.

**Comment by Slind14** [comment]
Multiworld the none supported world plugin works fine with 1.7

**Comment by mindforger** [comment]
i can remember there was an issue with the dimension ID somehow with negative numbers and numbers beyond 128 in the past?! ignore/delete this if not relevant

**Comment by ghost** [comment]
@Slind14 What version of Cauldron?

**Comment by devryb** [comment]
Multiworld has issues with some mods like Mariculture so not a good alternative
http://pastebin.com/NPabhXPK

**Comment by Katelyn-SN** [comment]
Confirmed issue with the following modpack and configuration:
- 1.0.1 Direwolf20 1.7
- Cauldron 2.0.9
- Multiverse 2.5
- Bungeecord 1.7.10 latest

**Comment by devryb** [comment]
Appears to be working for me in test build 211.  Relogged 3 times in a mv world I created on a test server running behind bungee.
Will test more tomorrow on my live servers.  Anyone else confirm this?
Looks like the rcon issues is probably the cause then as linked here

Edit: nvm looks like when the client is restarted the crashes start.  Ignore me :)

**Comment by bloodmc** [comment]
@Nentify @tf101-wizard @Slind14 @mindforger @Rhonim @devryb I finally had some time to take a look at this issue and have found where the problem lies. Let me explain a bit =)

Upon logging into a MultiWorld/MultiVerse world, Cauldron sends a DimensionRegisterPacket to the client in order to inform Forge's DimensionManager about the server's dimension and world provider. This is required since the server creates the world and not the client so the client must know about it on it's side. With BungeeCord, the DimensionRegisterPacket does indeed make it to Bungee from Cauldron but gets ignored during the login process which then causes the client to crash. This should be fixed soon so stay tuned.

**Comment by bloodmc** [comment]
@Nentify @tf101-wizard @Slind14 @mindforger @Rhonim @devryb All fixed =), I'll be making a PR to BungeeCord shortly.

**Comment by Katelyn-SN** [comment]
Very good! :)

**Comment by bloodmc** [comment]
@Nentify @tf101-wizard @Slind14 @mindforger @Rhonim @devryb Fixed in PR below
https://github.com/SpigotMC/BungeeCord/pull/1283

Here is a temp link until PR is merged

https://www.dropbox.com/s/z7pwieaudaft5fu/BungeeCord-Cauldron-B1.jar?dl=0

Enjoy!

**Comment by nightstalker6669** [comment]
@bloodmc just gave the above jar a test go, and it works great except for when I go to a spigot server from a cauldron server, then back to cauldron server it kicks me to desktop with this error in the bungee console.
http://pastebin.com/dmx6K6Ce

crash report from client: http://pastebin.com/FjefRde3

and client console output at the time of crash: http://pastebin.com/VJ2R1Acj

i hope that helps.

this is using latests cauldron (212), and git-Spigot-1.7.9-R0.2-205-g6a8d903 (MC: 1.7.10) with the above bungeecord build posted.

**Comment by bloodmc** [comment]
@nightstalker6669 Caused by immibis core mod attempting to add a pipeline when it already exists. He will need to add support for FML's reset handshake process. A simple check to see if pipeline exists or not would fix this specific problem.

**Comment by nightstalker6669** [comment]
@bloodmc thanks bloodmc for the response, i'll see if i can find his github repo and open a ticket referencing this. thanks again.

**Comment by bloodmc** [comment]
@nightstalker6669 Fixed in Immibis Core 59.0.5 update which can be found below

http://immibis.com/mcmoddl/files/immibis-core-59.0.5.jar

**Comment by nightstalker6669** [comment]
@bloodmc wow, you amaze me again bloodmc, thanks for that update, and keep up the outstanding work!

**Comment by JayPeaSize** [comment]
@bloodmc Appear to be having the issue still.
http://pastebin.com/T8GL3u3A

**Comment by bloodmc** [comment]
@Rhonim redownload https://www.dropbox.com/s/z7pwieaudaft5fu/BungeeCord-Cauldron-B1.jar?dl=0
I made another change to it yesterday.

**Comment by JayPeaSize** [comment]
@bloodmc Using that file currently.. downloaded/tested it just before I posted last. I'll try it again just in case. EDIT: Same result

**Comment by bloodmc** [comment]
@Rhonim Are you using multiverse? Explain EXACTLY the steps it takes to reproduce. Also create a fresh new world using MV and test again using the new one.

**Comment by JayPeaSize** [comment]
@bloodmc Yes, I'm using multiverse, Logging into server -> switch to other world -> die -> close client -> relog -> switch to server -> error

I'm guessing its due to the death. I'll test it normally here in a moment.

EDIT: Yeah, its due to the death and/or the attempt to respawn on connect. Sorry for not mentioning this before! Was doing it this way because that is how many of my player base managed to do it in the first place.

**Comment by JayPeaSize** [comment]
@bloodmc Any news on this?

**Comment by Katelyn-SN** [comment]
Cauldron development has been stopped so I don't think this will be fixed.
