### ISSUE TITLE
Power Armor Durability

### ISSUE THREAD

**Issue by devryb** [MinecraftPortCentral/Cauldron-Issues#72]
On a server running Cauldron Power Armor (From modular powersuits) loses durability (Not power charge) when damaged from mobs.
This issue doesn't occur in single player

Tested with Direwolf20 1.0.1 modpack and Cauldron build 209

**Comment by JackEF** [comment]
I can confirm this bug for other mods as well, e.g. Industrial Craft 2. The armors in IC2 ("nano" and "quantum") usually can not be destroyed and just stay at 0% (without giving any protection) in the armor equipment slots if they are depleted. 
On Cauldron on the other hand, they are destroyed and removed from the inventory permanently. This does neither occur on SP nor MP using vanilla servers with forge only.

**Comment by nister6000** [comment]
I also confirm, please fix it fast!

**Comment by bloodmc** [comment]
@devryb @JackEF @nister6000 Please confirm that this has been fixed in build 210

**Comment by JackEF** [comment]
Thanks for the update! Unfortunately, for IC2, the error still persists. Is there any way we can help you in identifying the problem?

In case it helps, here are some detailed steps to reproduce:
1. Start the Server and Game
2. Put on discharged (faster) or charged (takes some time to drain the energy) "Nano Suite Boots"
3. Take damage (e.g. stay in lava)
4. Armor disappears in armor slots once the energy is depleted and it takes further damage (will not disappear running vanilla forge)

Tested on: 
git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.210
industrialcraft-2-2.2.653-experimental

**Comment by bloodmc** [comment]
OK I'll work on a fix soon. Thanks

**Comment by bloodmc** [comment]
@JackEF @devryb @nister6000 OK I believe I have it fixed properly now. If you can test, go to cauldron.minecraftforge.net and click chat to join my channel. Ask for blood when you arrive =)

**Comment by bloodmc** [comment]
@JackEF @devryb @nister6000 Please test this bps patch to see if it fixes issue

https://www.dropbox.com/s/bip93ysgb0489vs/CauldronInstallerPatch-1.1236.05.211-TEST.bps?dl=0

**Comment by devryb** [comment]
Appears fixed for me with power suits, I tested quantum too and that never disappeared on me when I tested.

**Comment by bloodmc** [comment]
Fixed in build 211.

**Comment by LaoTheLizard** [comment]
I confirm. Fixed. Although, chestplate loses 2 hp yet (not critical).
No-PVP and godmode fixed.
Thanks a lot.
